name: Refresh README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    if: "!contains(github.event.head_commit.message, 'chore: update streak cache')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update streak cache
        run: |
          sed -i "s/&v=[^\"']*/\&v=$(date +%s)/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: update streak cache"
          git push
